# 请保护个人隐私信息，不要将此文件上传到公共仓库,不要在这个文件里面填写信息
# 请将此config.yaml复制并重命名为config_private.yaml
# 并将个人隐私信息填写到config_private.yaml中

# email之类的自行Google,如何开启IMAP服务
email_config:
  imap_url: "l3071635955@163.com"
  password: "HZ************TG"
  username: "imap.163.com"

notion_config:
  database_id: "c1a348********************4c7"    # 数据库ID
  token: "secret_OHvKVP*******************Lq" # token